// actionTypes.js
export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

export const PROCESS_UPDATE_BOOKING_REQUEST = 'PROCESS_UPDATE_BOOKING_REQUEST';
export const PROCESS_UPDATE_BOOKING_SUCCESS = 'PROCESS_UPDATE_BOOKING_SUCCESS';
export const PROCESS_UPDATE_BOOKING_FAILURE = 'PROCESS_UPDATE_BOOKING_FAILURE';

export const CREATE_UPDATE_BOOKING_REQUEST = 'CREATE_UPDATE_BOOKING_REQUEST';
export const CREATE_UPDATE_BOOKING_SUCCESS = 'CREATE_UPDATE_BOOKING_SUCCESS';
export const CREATE_UPDATE_BOOKING_FAILURE = 'CREATE_UPDATE_BOOKING_FAILURE';

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE';

export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAILURE = 'GET_BOOKING_FAILURE';

export const GET_UPDATE_BOOKING_REQUEST_REQUEST = 'GET_UPDATE_BOOKING_REQUEST_REQUEST';
export const GET_UPDATE_BOOKING_REQUEST_SUCCESS = 'GET_UPDATE_BOOKING_REQUEST_SUCCESS';
export const GET_UPDATE_BOOKING_REQUEST_FAILURE = 'GET_UPDATE_BOOKING_REQUEST_FAILURE';

export const GET_BOOKING_HISTORY_REQUEST = 'GET_BOOKING_HISTORY_REQUEST';
export const GET_BOOKING_HISTORY_SUCCESS = 'GET_BOOKING_HISTORY_SUCCESS';
export const GET_BOOKING_HISTORY_FAILURE = 'GET_BOOKING_HISTORY_FAILURE';


export const GET_ALL_BOOKINGS_REQUEST = 'GET_ALL_BOOKINGS_REQUEST';
export const GET_ALL_BOOKINGS_SUCCESS = 'GET_ALL_BOOKINGS_SUCCESS';
export const GET_ALL_BOOKINGS_FAILURE = 'GET_ALL_BOOKINGS_FAILURE';